# makefile - LociTerm client directory
#
# This makefile cd's to the topmost directory, and calls make from there.  This
# is here as a convenience. My IDE likes to call a makefile in the local
# directory whenever the make button is hit.

# Created: Fri Sep 13 10:07:32 AM EDT 2024 malakai
# $Id: makefile,v 1.1 2024/09/13 14:32:58 malakai Exp $

# Copyright © 2024 Jeff Jahr <malakai@jeffrika.com>
#
# This file is part of LociTerm - Last Outpost Client Implementation Terminal
#
# LociTerm is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# LociTerm is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with LociTerm.  If not, see <https://www.gnu.org/licenses/>.
#


all: 
	(cd ../..; make)

